version: '2'

services:

  mauticdb:
    image: percona/percona-server:5.7
    container_name: mauticdb
    environment:
      - MYSQL_ROOT_PASSWORD=mysecret
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - mautic-net

  mautic:
    image: andatamautic:latest
    container_name: mautic
    links:
      - mauticdb:mysql
    depends_on:
      - mauticdb
    ports:
      - 8080:80
    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MYSQL_PORT_3306_TCP=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mysecret
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_RUN_CRON_JOBS=true
      - MAUTIC_SITE_URL=http://localhost:8080
      - MAUTIC_MAILER_FROM_NAME="Big Tester"
      - MAUTIC_MAILER_HOST=localhost
      - MAUTIC_MAILER_FROM_EMAIL=local@localhost
      - MAUTIC_ADMIN_PASSWORD=mautic123
      - MAUTIC_MODE=docker
    networks:
      - mautic-net

volumes:
  mysql_data:
    driver: local
  mautic_data:
    driver: local
networks:
  mautic-net:
    driver: bridge